# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches:
      - dev
      - master
    
env:
  SERVERLESS_PLATFORM_VENDOR: tencent
  TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
  TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.ref}}
      - name: clone local repository
        uses: actions/checkout@v2
      - name: npm install
        run: npm install
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: deploy
        uses: June1991/serverless-action@master
        with:
          args: --debug
          stage: prod 
