# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches:
      - '*'

env:
  SERVERLESS_PLATFORM_VENDOR: tencent
  TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
  TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
  

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: clone local repository
        uses: actions/checkout@v2
      - name: install serverless
        run: npm install serverless
      - name: install dependency
        run: npm install
      - name: build
        run: npm build
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: unit test
        run: '' 
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [build,test]
    steps:
      - name: deploy serverless
        run: sls deploy --debug --inputs.stage='dev'
        
